### ISSUE TITLE
Consolidate custom product and custom order shipment into order shipment

### ISSUE THREAD

**Issue by Mark-H** [poconosewandvac/Commerce_DigitalProduct#1]
Right now some fields are added to the product form through the custom product (e.g. file/resource), while others (e.g. max downloads) are added through the order shipment. 

Ideally, I think all of that should be put into the order shipment. Simpler, and that's the right extension point for anything delivery-related. Custom products should mostly be used when product information has to be collected from a custom source, or generated on-demand. 

If you came across limitations with the order shipment that led you to put some stuff into the product, perhaps there's something I can do about that in Commerce?

**Comment by tonyklapatch** [comment]
I was thinking more that the file/download information belonged to the product, but I can see why it should be on the shipment (since it gets added to its own custom table anyways). I'll move it to the shipment for the next release.

**Comment by tonyklapatch** [comment]
Now uses shipment fields in v1.1.0.
